apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/admission-webhook/upstream/overlays/cert-manager?ref=v1.7.0

## Cert Manager
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha2
      kind: 'Certificate|Issuer'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: cert-manager.io/v1
