---
# k3d cluster create local --config=cluster/config.yaml
apiVersion: k3d.io/v1alpha2
kind: Simple
name: kubeflow
image: rancher/k3s:v1.21.7-k3s1
servers: 1
agents: 1
options:
  k3d:
    wait: true
    disableHostIPInjection: true
  k3s:
    extraServerArgs:
    - --disable
    - traefik
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer
- port: 443:443
  nodeFilters:
  - loadbalancer
