apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/apps/katib/upstream/installs/katib-with-kubeflow?ref=v1.7.0

images:
- name: mysql
  newName: mysql
  newTag: 8.0.22

## Cert Manager
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha2
      kind: 'Certificate|Issuer'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: cert-manager.io/v1
