apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
  namespace: istio-system
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  CLIENT_SECRET: 'XXXXXX'
  CLIENT_ID: XXXXXX
  namespace: istio-system
  OIDC_AUTH_URL: https://login.microsoftonline.com/XXXXXX/oauth2/v2.0/authorize
  OIDC_PROVIDER: https://login.microsoftonline.com/XXXXXX/v2.0
  REDIRECT_URL: https://kubeflow.example.ca/login/oidc
  SKIP_AUTH_URI: ""
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ""
  USERID_CLAIM: preferred_username
  OIDC_SCOPES: profile email
  PORT: "8080"
  STORE_PATH: /var/lib/authservice/data.db
