apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- github.com/kubeflow/manifests/apps/profiles/upstream/overlays/kubeflow?ref=v1.7.0


configMapGenerator:
- name: namespace-labels-data
  behavior: merge
  files:
  - namespace-labels.yaml

      
patchesStrategicMerge:
- deployment.yaml
