apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow
data:
  ingress: |-
    {
        "ingressGateway" : "ingress-general-system/general-istio-ingress-gateway-https",
        "ingressService" : "general.ingress-general-system.svc.cluster.local"
    }
