apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/manifests/contrib/kserve/kserve?ref=v1.7.0
- authorizationpolicy.yaml
- cluster-local-gateway.yaml

patchesStrategicMerge:
- inferenceservice-configmap.yaml

## Cert Manager
patchesJson6902:
  - target:
      group: cert-manager.io
      version: v1alpha2
      kind: 'Certificate|Issuer'
      name: '.*'
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: cert-manager.io/v1
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: 'MutatingWebhookConfiguration'
      name: 'inferenceservice.serving.kserve.io'
    patch: |-
      - op: remove
        path: "/webhooks/1/namespaceSelector"
